### ISSUE TITLE
List Produit Crashes the App

### ISSUE THREAD

**Issue by KeitelDOG** [TransitDigitale/SIMApp#122]
When clicking to Produit in Menu Drawer, the App crashes. I don't know who worked on it and who to assign. I assign @jetprog . So you can assign another one.

@TransitDigitale/transitiondigitale

**Comment by KeitelDOG** [comment]
Error in ProduitRefAdapter : 

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        // get the Showbiz
        Produit_Ref produit = getItem(position);

        // find or inflate the template
        if (convertView == null) {
            LayoutInflater inflater = LayoutInflater.from(getContext());
            convertView = inflater.inflate(R.layout.item_list_product, parent, false);
        }
        TextView tvNameOfProduct = (TextView) convertView.findViewById(R.id.tvName);
        tvNameOfProduct.setText(produit.getNom_Produit().toString());

         TextView tvCategorie = (TextView) convertView.findViewById(R.id.tvCategorieProduct);
         //Error when i load  getNom_Produit
        // tvCategorie.setText(produit.getNom_Produit().toString());
        tvCategorie.setText(produit.getCategorie().getCategorie_Desc().toString().trim());

        return convertView;
    }

The error is on line : 

    tvNameOfProduct.setText(produit.getNom_Produit().toString());

Probably because R.id.tvName does not exist anymore : 

    TextView tvNameOfProduct = (TextView) convertView.findViewById(R.id.tvName);

**Comment by KeitelDOG** [comment]
@jetprog  corrected it in recent commit.

**Comment by jetprog** [comment]
yeah bro @KeitelDOG , now is ok...
