### ISSUE TITLE
Create Adapters File 

### ISSUE THREAD

**Issue by cbaja** [TransitDigitale/SIMApp#13]
![data_model](https://cloud.githubusercontent.com/assets/11256198/19108393/4becdeba-8ab6-11e6-85af-a01aab021255.png)

Just the structure of the java file

@TransitDigitale/transitiondigitale

**Comment by ingdjason** [comment]
adapter takes data in a model and model is not created ... u can define the tables 4 the new adapters @cbaja

**Comment by ingdjason** [comment]
mon anglais n' pas parfait @cbaja @juliofihdeldev @Marcedwin0 @KeitelDOG @jfstephane

**Comment by ingdjason** [comment]
don't have control, i need to recapture the team `please`

**Comment by cbaja** [comment]
@ingdjason let's me on Saturday to fix all the issues about the project
@TransitDigitale/transitiondigitale

**Comment by ingdjason** [comment]
ok!!!
