### ISSUE TITLE
About the MainActivity

### ISSUE THREAD

**Issue by jetprog** [TransitDigitale/SIMApp#134]
avan last code sa yo, nan branch ki rele addProductToBackendless lan, ActionBar lan pran nom marche an san prob epi entete drawer an pran usermail lan normal san pran tan, eseye konpare kod sa ak new MainActivity nou genyen now lan bro, swiv saw we ki k lakoz now li pran plus tan pou sa yo paret e ase souvan li pa paret menm. 
Li plus ke yn kesyn bn entenet au final, li pa sa selman gen yn ti prob geleu, wa banm feedback bro @KeitelDOG

**Comment by KeitelDOG** [comment]
Eske ou sur ke se pa le ou te fek login sou li? Paske le ou fek login Backendless.UserService.CurrentUser() as gen object User a ladan li alors li pap bezwen reload li alor li afiche pi rapid

**Comment by KeitelDOG** [comment]
@jetprog , @juliofihdeldev , Men si nou vle mwen afiche yo alors m ka mete (nom marche, email ak UserName) nan shared preferences pou li afiche an lagan.

**Comment by juliofihdeldev** [comment]
esa m tap tou wi bro
