### ISSUE TITLE
Backendless data model

### ISSUE THREAD

**Issue by cbaja** [TransitDigitale/SIMApp#15]
http://develop.backendless.com/#SIMA/v1/main/home

Please let me know if you can access the data model

@TransitDigitale/transitiondigitale

**Comment by jetprog** [comment]
no access, what account you use?

**Comment by cbaja** [comment]
I used my google account. Do you know how i can give other people access to the same database on backendless.
@TransitDigitale/transitiondigitale

**Comment by cbaja** [comment]
Jethro please try to see how we can do that?

@TransitDigitale/transitiondigitale

**Comment by jetprog** [comment]
@cbaja  the only way u can invite someone like collaborator on a same database is not free, you will send invitation by mail.. @TransitDigitale/TransitionDigitale
