### ISSUE TITLE
MainActivity

### ISSUE THREAD

**Issue by jetprog** [TransitDigitale/SIMApp#156]
A propos des points de vente, ils (Les utilisateurs(Admin)) sont  d'avis pour que ça soit fixer a  9 points de vente.(L'agent de saisie n'aura pas a creer lui-meme ces derniers)

**Comment by cbaja** [comment]
Any update from you @KeitelDOG 
@TransitDigitale/transitiondigitale

**Comment by KeitelDOG** [comment]
However, I just put a limit = 9 to the number of CollecteHD that can be created. I also put a progressbar on the Menu Items (Add - Delete)

If you want all 9 CollecteHD to be created at once, we should create them when we are creating a Marche_Ref object.
