### ISSUE TITLE
Create Fragments for Marche, Produits, categories, etc..

### ISSUE THREAD

**Issue by cbaja** [TransitDigitale/SIMApp#16]
Create a main container for those fragments and call them when you click on menu drawer. In the collectActivity
Julio where are you this issue is for you.
@TransitDigitale/transitiondigitale

**Comment by juliofihdeldev** [comment]
i 'm here i ll push iti soon as i got a internet connexion !!!

**Comment by cbaja** [comment]
Julio i put more task for you.

@TransitDigitale/transitiondigitale

**Comment by juliofihdeldev** [comment]
i am on it

**Comment by cbaja** [comment]
Julio please review your change about the fragments. 
You have any issues please let me know.
Are you coming in my office tomorrow morning.
@TransitDigitale/transitiondigitale
