### ISSUE TITLE
Add field commentaire in the collectedDT

### ISSUE THREAD

**Issue by cbaja** [TransitDigitale/SIMApp#163]
@TransitDigitale/transitiondigitale

**Comment by cbaja** [comment]
Dont forget the date and time of the collect 

@KeitelDOG

**Comment by KeitelDOG** [comment]
I did it.
![image](https://cloud.githubusercontent.com/assets/14042152/20506520/b2cd43ae-b022-11e6-98e5-98c7cb421308.png)

![image](https://cloud.githubusercontent.com/assets/14042152/20506538/c9078526-b022-11e6-832f-44b6434d4571.png)
