### ISSUE TITLE
When the "produit inconnu" est affiche dans la liste collectedDT the App crash

### ISSUE THREAD

**Issue by cbaja** [TransitDigitale/SIMApp#182]
When a user try to Edit or Delete that product items in the list the app crash.

@TransitDigitale/transitiondigitale

**Comment by cbaja** [comment]
![screenshot 2016-11-21 21 57 45](https://cloud.githubusercontent.com/assets/11256198/20509290/9fe614ec-b035-11e6-94fb-409ab5b72a16.png)

**Comment by KeitelDOG** [comment]
I fixed the problem. The thing is when a Produit_Ref parent is deleted, it leaves orphan CollecteDT children.

That's why some CollecteDT has empty Produit_Ref relation
