### ISSUE TITLE
Nettoyage des listes:  

### ISSUE THREAD

**Issue by ingdjason** [TransitDigitale/SIMApp#192]
Verification, modification et ajout de nouveau data dans list catégorie et list produits.(Modifier par les employer du SIMA) @TransitDigitale/transitiondigitale

**Comment by cbaja** [comment]
Messieurs, Priere de reverifier les categories des produits. Parce que certaines categories non pas de produits. Ce qui plante l'application. Si cette categorie ne contient pas de produits reellement mettez le nom de la categorie comme produits par defaut. Exemple de cas
Categorie : Poisson
Produits    : Poisson

Categorie : Radis
Produits   : Radis

@TransitDigitale/transitiondigitale

**Comment by jetprog** [comment]
everything is right now...
