### ISSUE TITLE
Build Tools Gradle keeps changing

### ISSUE THREAD

**Issue by KeitelDOG** [TransitDigitale/SIMApp#195]
classpath 'com.android.tools.build:gradle:2.2.2'

I can't work with 2.2.2

2.2.1 is the max I can use

Should all of us update to 2.2.2? I can update tomorrow at work!

**Comment by cbaja** [comment]
Maybe Julio steel change it in his project. We already set the value to 2.2.1. 
Julio please put your classpath 'com.android.tools.build:gradle:2.2.1' like this.
Thanks

@juliofihdeldev 

@TransitDigitale/transitiondigitale

**Comment by juliofihdeldev** [comment]
ok bro

2016-11-28 4:34 GMT-07:00 Keitel Jovin <notifications@github.com>:
