### ISSUE TITLE
Add more field on the register fragment 

### ISSUE THREAD

**Issue by cbaja** [TransitDigitale/SIMApp#20]
Add more field on the register fragment base on the wireframe below.

![registeractivity](https://cloud.githubusercontent.com/assets/11256198/19131765/56692cc6-8b16-11e6-8f8c-48a36556ccbc.png)

@TransitDigitale/transitiondigitale

**Comment by juliofihdeldev** [comment]
i don't put code Utilisateur cause i think it ll be gerenate itself
