### ISSUE TITLE
Can you try to catch in memory the last info entered in the previous point de vente

### ISSUE THREAD

**Issue by cbaja** [TransitDigitale/SIMApp#232]
Scenarios 1 : we are on "POINT5"
We entered those info in the screen below: 
![screenshot_2016-12-13-14-29-22](https://cloud.githubusercontent.com/assets/11256198/21155593/b7de5c50-c140-11e6-859c-c6609f0d3cac.png)

After save them on the cloud. when i am going to a next point de vente "POINT6" i would to propose the same info except those fields should be blank .
Prix(Gdes) ____
Poids(Kg)______
Commentaires_____

Guys please give me your feedback about this.

@TransitDigitale/transitiondigitale

**Comment by KeitelDOG** [comment]
Sounds like a good idea. I don't knoww if in reality agent would jump from a real point vente to another collecting the same product.
However I think he might even collecting same product with multiple Unite, and would need the last product he used before.

We could save the last Categorie, Produit, Unite, Provenance in Static variables in CollecteItems Class, and then auto select them in Spinners when adding new CollecteDT

**Comment by cbaja** [comment]
Yes you catch it. The agent will win time by using this approach.
