### ISSUE TITLE
Create Table Unite in Backendless

### ISSUE THREAD

**Issue by KeitelDOG** [TransitDigitale/SIMApp#56]
Add a table Unite_Ref in Banckendless database, to link with ForeignKey (unite - smallint) in table ColecteDT:

CollectDT
- ID -> bigint
- CollecteID -> bigint
- ProduitID -> bigint
- Unite -> smallint

Unite_Ref
- ID -> smallint
- Unite_Desc -> varchar(50)

**Comment by cbaja** [comment]
I added the table yesterday night

@TransitDigitale/transitiondigitale
