### ISSUE TITLE
Push data collecte on backendless

### ISSUE THREAD

**Issue by cbaja** [TransitDigitale/SIMApp#59]
@TransitDigitale/transitiondigitale

**Comment by KeitelDOG** [comment]
@jetprog Can you give me some example of codes on how to push data on Backendless?

**Comment by cbaja** [comment]
Button btnSave = (Button)view.findViewById(R.id.btnSave);
        btnSave.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                Product product = new Product();

                product.productName="Avocat";
                product.buyingPrice=2.5d;
                product.sellingPrice=3.5d;

                Market market = new Market();
                market.products = new ArrayList<>();
                market.products.add(product);


                Backendless.Data.of(Product.class).save(product, new AsyncCallback<Product>() {
                    @Override
                    public void handleResponse(Product product) {
                        Toast.makeText(getActivity(),"save successfully!",Toast.LENGTH_LONG).show();
                    }

                    @Override
                    public void handleFault(BackendlessFault backendlessFault) {
                        Toast.makeText(getActivity(),"error!",Toast.LENGTH_LONG).show();
                    }
                });

            }
        });

@KeitelDOG  You can inspire from that snippet to save data on backendless. It will be implemented on the onCreateView method.

@TransitDigitale/transitiondigitale

**Comment by KeitelDOG** [comment]
Resolve with Pull Request #103
