### ISSUE TITLE
App blocked on SplashScreen

### ISSUE THREAD

**Issue by KeitelDOG** [TransitDigitale/SIMApp#71]
Uncomment the intent call after Login:

`public void stayLoginFunction(){
        final String userToken = HeadersManager.getInstance().getHeader( HeadersManager.HeadersEnum.USER_TOKEN_KEY );

        if (null == userToken) {
            Intent mainIntent = new Intent(SplashScreen.this,Login.class);
            startActivity(mainIntent);
            finish();
        }else{
            Toast.makeText(getApplicationContext(),"Bon retour "+userToken , Toast.LENGTH_SHORT).show();
            //Intent mainIntent = new Intent(SplashScreen.this,MainActivity.class);
            //startActivity(mainIntent);
            //finish();
        }
    }`

**Comment by cbaja** [comment]
Bug fixed by the last PR

@TransitDigitale/transitiondigitale
